export enum Role {
  ADMIN = 'ADMIN',
  LOCAL = 'LOCAL',
  CONSULTANT = 'CONSULTANT',
  COMPANY_EMPLOYEE = 'COMPANY_EMPLOYEE',
  SUPPORT = 'SUPPORT',
  UNDEFINED = 'UNDEFINED'
}

export enum PhoneType {
  MOBILE = 'MOBILE',
  HOME_PHONE = 'HOME_PHONE'
}
